{{- if .Values.rbac.enabled -}}
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: {{ include "helm.fullname" . }}
rules:
  - apiGroups:
      - ""
    resources:
      - configmaps
    resourceNames:
{{- if .Values.whitelistsConfigMap.ref.name }}
      - {{ .Values.whitelistsConfigMap.ref.name }}
{{- else }}
      - {{ include "helm.fullname" . }}
{{- end }}
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - extensions
    resources:
      - ingresses
    verbs:
      - get
      - list
      - watch
      - update
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: {{ include "helm.fullname" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "helm.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "helm.fullname" . }}
    namespace: {{ .Release.Namespace }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "helm.fullname" . }}
  namespace: {{ .Release.Namespace }}
{{- end -}}