{{- if not .Values.whitelistsConfigMap.ref.name -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "helm.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "helm.name" . }}
    helm.sh/chart: {{ include "helm.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
{{- with .Values.whitelistsConfigMap.content }}
{{ tpl . $ | indent 4 }}
{{- end }}
{{- end -}}
